// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7tWlUW7QYicuhI8g9AnTdL53q7725kXs',
    appId: '1:711540209128:web:7474876edacde48a2aa05d',
    messagingSenderId: '711540209128',
    projectId: 'chatapp-c596e',
    authDomain: 'chatapp-c596e.firebaseapp.com',
    storageBucket: 'chatapp-c596e.firebasestorage.app',
    measurementId: 'G-04RVJNB66K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa8w43yiyOo_UW8nsQOSxsKWe7l7DV-wI',
    appId: '1:711540209128:android:daae60ccba95f83d2aa05d',
    messagingSenderId: '711540209128',
    projectId: 'chatapp-c596e',
    storageBucket: 'chatapp-c596e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS2EcBZtPNcssk7iiUXaKfEJLitqq75fc',
    appId: '1:711540209128:ios:fc0621dc4a66655a2aa05d',
    messagingSenderId: '711540209128',
    projectId: 'chatapp-c596e',
    storageBucket: 'chatapp-c596e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS2EcBZtPNcssk7iiUXaKfEJLitqq75fc',
    appId: '1:711540209128:ios:fc0621dc4a66655a2aa05d',
    messagingSenderId: '711540209128',
    projectId: 'chatapp-c596e',
    storageBucket: 'chatapp-c596e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7tWlUW7QYicuhI8g9AnTdL53q7725kXs',
    appId: '1:711540209128:web:2ef9f1d35de40a7a2aa05d',
    messagingSenderId: '711540209128',
    projectId: 'chatapp-c596e',
    authDomain: 'chatapp-c596e.firebaseapp.com',
    storageBucket: 'chatapp-c596e.firebasestorage.app',
    measurementId: 'G-8ZMMJT3YM5',
  );
}
